version: 2.1

commands:
  prepare:
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: com.workframe.{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "deps.edn" }}-2

executors:
  clojure:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.9.0.397
    environment:
      JAVA_OPTS: "-Xms512m -Xmx3200m"

jobs:
  dependencies:
    executor: clojure
    steps:
      - prepare
      - run:
          clojure -A:garamond -Spath
          clojure -A:test -Spath
          clojure -A:jar -Spath
      - save_cache:
          key: com.workframe.{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "deps.edn" }}-2
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ~/.clojure
            - .cpcache
  test:
    executor: clojure
    steps:
      - prepare
      - run: clojure -A:test
      - store_test_results:
          path: target
  build:
    executor: clojure
    steps:
      - prepare
      - run: git fetch --tags
      - run: clojure -A:garamond -a garamond -g com.workframe --pom
      - run: cp pom.xml target
      - run: clojure -A:jar
      - persist_to_workspace:
          root: target
          paths:
            - target/garamond.jar
            - target/pom.xml
      - store_artifacts:
          path: target
  deploy:
    executor: clojure
    steps:
      - prepare
      - attach_workspace:
          at: target
      - run: cp target/pom.xml .
      - run: echo clojure -A:deploy

workflows:
  version: 2
  test:
    jobs:
      - dependencies:
          filters:
            branches: { only: /.*/ }
      - test:
          requires:
            - dependencies
  deploy:
    jobs:
      - dependencies:
          filters:
            tags: { only: /^v.*/ }
            branches: { ignore: /.*/ }
      - test:
          requires:
            - dependencies
          filters:
            tags: { only: /^v.*/ }
      - build:
          requires:
            - test
          filters:
            tags: { only: /^v.*/ }
      - deploy:
          requires:
            - build
          filters:
            tags: { only: /^v.*/ }
